"""Training loop and ridge fit behavior on synthetically labeled data."""

from __future__ import annotations

import torch

from gnff.evaluate import evaluate_potential
from gnff.models import AcsfNet, MpnnConfig, MpnnPotential, RidgePotential
from gnff.train import TrainSettings, train_potential


def test_ridge_recovers_linear_oracle(labeled_frames):
    """Labels generated by a linear ACSF model are fit almost exactly."""
    model = RidgePotential()
    train, val = labeled_frames[:24], labeled_frames[24:30]
    report = model.fit(train, val, alphas=(1e-10,), force_weight=0.1)
    e_mae, f_mae = evaluate_potential(model, labeled_frames[30:])
    assert e_mae < 0.5  # meV/atom
    assert f_mae < 5.0  # meV/A
    assert report["chosen_alpha"] == 1e-10


def test_ridge_alpha_selection_prefers_better_val(labeled_frames):
    model = RidgePotential()
    report = model.fit(
        labeled_frames[:24], labeled_frames[24:30], alphas=(1e-10, 10.0), force_weight=0.1
    )
    assert report["chosen_alpha"] == 1e-10


def test_mpnn_training_reduces_error(labeled_frames):
    torch.manual_seed(0)
    model = MpnnPotential(MpnnConfig(hidden=16, n_blocks=2, n_rbf=8, cutoff=5.0))
    train, val = labeled_frames[:24], labeled_frames[24:30]
    model.set_reference(train)
    e0, f0 = evaluate_potential(model, val)
    report = train_potential(
        model,
        train,
        val,
        TrainSettings(epochs=8, batch_size=8, lr=3e-3, force_weight=0.1, val_every=2, seed=0),
    )
    e1, f1 = evaluate_potential(model, val)
    # The per-element reference already explains most of the energy on this
    # near-linear oracle (e0 is small by construction), so the meaningful
    # checks are that optimization progresses and forces improve.
    assert e0 > 0 and e1 > 0
    assert f1 < f0
    assert report["history"][-1]["train_loss"] < report["history"][0]["train_loss"]
    assert report["best_epoch"] is not None
    assert len(report["history"]) == 8


def test_acsf_net_training_runs_and_selects_best(labeled_frames):
    torch.manual_seed(0)
    model = AcsfNet(hidden=(8, 8))
    report = train_potential(
        model,
        labeled_frames[:16],
        labeled_frames[24:28],
        TrainSettings(epochs=4, batch_size=8, lr=3e-3, force_weight=0.1, val_every=2, seed=0),
    )
    assert report["best_epoch"] is not None
    # scaler was fitted: no zero stds
    assert float(model.feat_std.min()) > 0.0
